### ISSUE TITLE
selectInteraction option doesn't seem to work

### ISSUE THREAD

**Issue by MatteoManfredi** [molstar/pdbe-molstar#105]
Reading the documentation, it seems like setting this option to false should make it so that clicking on a residue will not show the side chains of nearby residues. However, nothing seems to change.
I tried adding the option to the different working examples provided on this repo, as well as on my application.

If the behaviour of this option is different, is there any other way to make it so that side chains are never shown when clicking on the residues?

**Comment by MatteoManfredi** [comment]
Just to clarify, I would like to know how to programmatically perform the same action of this button so that I can hide the surroundings after clicking on a residue. Not loading them altogether would be even better, but it is okay to just hide them or remove them after they are loaded.

![image](https://github.com/molstar/pdbe-molstar/assets/39552391/fba294ef-80b9-44fc-9a40-af9ffa50ee36)

**Comment by midlik** [comment]
Hi.
Try updating to version 3.2.0, it seems to work there.

Please notice, that we stopped deploying PDBe Molstar via https://www.ebi.ac.uk/pdbe/pdb-component-library/. You'll have to use these links instead:

```
<script src="https://cdn.jsdelivr.net/npm/pdbe-molstar@3.2.0/build/pdbe-molstar-plugin.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pdbe-molstar@3.2.0/build/pdbe-molstar-component.js"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pdbe-molstar@3.2.0/build/pdbe-molstar.css" />
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pdbe-molstar@3.2.0/build/pdbe-molstar-light.css" />
```

(it's a fresh change, I haven't had time to update the wiki yet, but will get to it soon)

**Comment by MatteoManfredi** [comment]
Thank you, I can confirm that the option now works fine!
