### ISSUE TITLE
CSS transform:scale cause molstar canvas to have incorrect size

### ISSUE THREAD

**Issue by TomasKulhanek** [molstar/pdbe-molstar#18]
We use the pdbe-molstar web component in our interactive documentation. 
In some cases we need the whole part of the web page to be smaller, therefore, we use CSS `transform: scale(0.5);transform-origin:top left;width:200%`  This cause the pdbe-molstar to be broken. The viewport (msp-viewport) have correct size. The canvas with molecule in white background has incorrect size (even smaller) as seen in the following screenshot:

![firefox_pTJ9hFF77T](https://user-images.githubusercontent.com/1429487/110948864-295d6980-8342-11eb-8312-b6ff7f209562.png)

Prepared plunker example of this error at https://plnkr.co/edit/pdmHZTULh3vUPq8e?preview

The canvas size should fit the div. This issue is present in chrome 88.0.4324.190, firefox 86.0, ms edge 88.0.705.74

**Comment by TomasKulhanek** [comment]
This issue is caused by resizeCanvas in molstar/src/mol-canvas3d/util.ts. Thus submitted as issue molstar/molstar#147

**Comment by mandarsd** [comment]
Thanks for reporting the issue in the Molstar core project. As the PDBe plugin is built on top of the Molstar core, ideally such issues get fixed when we update the core dependency to latest. I'll try to check if I could override just the resizeCanvas method to provide a quick fix

**Comment by mandarsd** [comment]
Mol* core dependency updated to v3.x
