### ISSUE TITLE
PDBe Ligand view

### ISSUE THREAD

**Issue by Jhsmit** [molstar/pdbe-molstar#45]
I'm having trouble getting the Ligand View to work

I'm using the webcomponent, using the example code on the wiki, together with the webcomponent plunk example:

```
<div id="myViewer">
<pdbe-molstar ligand-label-comp-id="REA" ligand-auth-asym-Id="A" ligand-auth-seq-id="200" ligand-hydrogens="true"></pdbe-molstar>
</div>
```

However, this does not render anything. Do I need to pass additional attributes such as molecule-id?

**Comment by mandarsd** [comment]
Yes, `molecule-id` attribute is mandatory -
Example  - `<pdbe-molstar molecule-id="1cbs" ligand-label-comp-id="REA"></pdbe-molstar>`
