### ISSUE TITLE
Serving PDB data without a server

### ISSUE THREAD

**Issue by ljmartin** [molstar/pdbe-molstar#52]
Hi PDBe-Molstar - this repo has been really useful, so thank you. 

I'd like to embed structure data into a single html file so that, for instance, I can send the visualization to a collaborator, who could view non-public structures without requiring them to open a local server hosting the PDB file. Is there some possible work-around to achieve this? Or could there be some other way to trick pdbe-molstar into thinking it's reading local datafiles via a url without actually using a server? I imagine it's possible with Molstar, but I love the simplicity of pdbe-molstar. 

Thanks
Lewis

**Comment by CrisSherban** [comment]
> Hi PDBe-Molstar - this repo has been really useful, so thank you.
> 
> I'd like to embed structure data into a single html file so that, for instance, I can send the visualization to a collaborator, who could view non-public structures without requiring them to open a local server hosting the PDB file. Is there some possible work-around to achieve this? Or could there be some other way to trick pdbe-molstar into thinking it's reading local datafiles via a url without actually using a server? I imagine it's possible with Molstar, but I love the simplicity of pdbe-molstar.
> 
> Thanks Lewis

HI @ljmartin, were you able to do this? I was also interested in how to pass the PDBs directly to the JS plugin.
