### ISSUE TITLE
How to preserve the initial style?

### ISSUE THREAD

**Issue by Fanyini** [molstar/pdbe-molstar#53]
Dear all,
Firstly, thanks again for the nice work! I am also really grateful for support and implementing features based on requests from people!
Below is my code，I want the initial protein structure to be presented in the "molecular-surface" form. Next, other protein structures are added to manifest themselves in the form of "spacefills".But it will all be updated to the "spacefill" form (including the initial protein structure).
` new Promise((resolve => {
        viewerInstance = new PDBeMolstarPlugin();
        viewerContainer = document.getElementById("pdbView");

        // console.log(resolve)
        resolve()
    })).then(() => {
        optionBall = {
            customData: {
                url: "http://127.0.0.1:5000/molStar/frameIndex", format: "pdb",
            }, visualStyle: "molecular-surface",
            hideControls: true,
        }
    }).then(() => {
        viewerInstance.render(viewerContainer, optionBall)
    }).then(() => {
        setTimeout(() => {
            viewerInstance.visual.update({
                customData: {
                    url: "http://127.0.0.1:5000/molStar/pocketIndex",
                    format: 'pdb',
                },
                visualStyle: "spacefill",
            }, false)
        }, 2000)
    })`

**Comment by mandarsd** [comment]
This feature is now implemented / available in recent v3.x
