### ISSUE TITLE
AlphaFold2 pLDDT coloring from B-factor fields not working

### ISSUE THREAD

**Issue by GrayWasTaken** [molstar/pdbe-molstar#56]
For some reason plDDT data represented in an mmCIF file alone is insufficient for coloring the structure by plDDT similar to the AlphaFold2 DB. Additionally, I can't find a guide for the proper formatting required for formatting an mmCIF file so that the `alphafoldView: true` will actually work.

Is there a guide or something for how to format mmCIF files so that `alphafoldView: true` will work?

**Comment by mandarsd** [comment]
We use the _ma_qa_metric_local category details from the AFDB mmcif to display the model confidence coloring. Your mmcif file must contain this category to view the representation with `alphafoldView: true` option
Please refer to [https://alphafold.ebi.ac.uk/files/AF-P08083-F1-model_v2.cif](https://alphafold.ebi.ac.uk/files/AF-P08083-F1-model_v2.cif) for ma_qa_metric_local category information

**Comment by GrayWasTaken** [comment]
Are there any tools or guides available for modifying the `_ma_qa_metric_local` field because it still isn't very clear to me how I should edit my current mmCIF files.

I reviewed http://rcsb-mmcif.rutgers.edu/dictionaries/mmcif_ma.dic/Categories/ma_qa_metric_local.html and I'm also wondering what each column represents within lines like `    1 1 A 20 LEU 1 -0.85`.

```
    loop_
    _ma_qa_metric_local.ordinal_id
    _ma_qa_metric_local.model_id
    _ma_qa_metric_local.label_asym_id
    _ma_qa_metric_local.label_seq_id
    _ma_qa_metric_local.label_comp_id
    _ma_qa_metric_local.metric_id
    _ma_qa_metric_local.metric_value
    1 1 A 20 LEU 1 -0.85
    1 1 A 21 ARG 2 -2.71
   # ...  abbreviated ...
```

**Comment by mandarsd** [comment]
Please contact the AlphaFold DB team for this information at - alphafold@deepmind.com and afdbhelp@ebi.ac.uk

**Comment by GrayWasTaken** [comment]
I think we should consider adding in a feature for coloring chains by their residue index or by their B factor field values as formatting cif files the same way that AFDB does isn't very practical for the average person.
