### ISSUE TITLE
Is it possible to add plane or surface after render?

### ISSUE THREAD

**Issue by S-Gutierrez** [molstar/pdbe-molstar#57]
First off, I would like to thank you for the great work you do with Molstar.

Regarding my question, I am trying to differentiate between different segments of the protein structure predicted by Alphafold. I changed the colour of the selected sequence of residues as shown below.

```
viewerInstance.render(viewerContainer, options);
      viewerInstance.events.loadComplete.subscribe(() => {viewerInstance.visual.select({ data: [{entity_id: '1', start_residue_number: 1, end_residue_number: 25, color:{r:1,g:22,b:0}}, {entity_id: '1', start_residue_number: 26, end_residue_number: 35, color:{r:22,g:255,b:0}}]})})
```

However, with this method, we lose the confidence information given by Alphafold. I was wondering if it is possible to do something similar to add a plane fitting a selected group of residues or a surface covering them.

I got my inspiration from this link:

https://molstar.org/viewer/?snapshot-url=https://molstar.org/viewer-docs/tips/measurements/plane.molx&snapshot-url-type=molx

Thanks in advance.

**Comment by mandarsd** [comment]
There is basic support for adding some built-in representation (https://github.com/molstar/molstar/blob/master/src/mol-repr/structure/registry.ts#L37)

You will have to use 'representation' and 'represtationColor' params. Example -
`viewerInstance.events.loadComplete.subscribe(() => {
        viewerInstance.visual.select({ data: [{entity_id: '1', start_residue_number: 1, end_residue_number: 10, representation: 'molecular-surface', representationColor:{r:1,g:22,b:0}}, {entity_id: '1', start_residue_number: 26, end_residue_number: 35, color:{r:22,g:255,b:0}}]})
      });`
      
 In the recent v3.x update the confidence info will not get lost after colouring.
 
 I'll soon update the wiki document with the representation and other param information.
