### ISSUE TITLE
Cannot open local file by using PDBe Molstar as web component

### ISSUE THREAD

**Issue by yongjuntan** [molstar/pdbe-molstar#59]
Hello,

I tried to load my own structure file in pdb format with below code. The mol* window could show normally, but fail to show the structure. (I could open the structure in PyMOL and use below path to open the file.)
In windows:
`<pdbe-molstar custom-data-url="file://C:\Users\yongj\Desktop\Tox-GHH.QDT78576.pdb" bg-color-r="255" bg-color-g="255" bg-color-b="255" hide-controls="true" custom-data-format="pdb"></pdbe-molstar>`

In linux:
<pdbe-molstar custom-data-url="file:///home/Tox-GHH.QDT78576.pdb" bg-color-r="255" bg-color-g="255" bg-color-b="255" hide-controls="true" custom-data-format="pdb"></pdbe-molstar>

Thanks for your help.

**Comment by mandarsd** [comment]
Hi,
You will have to provide the file using a local server, so the file path will look something like - http://localhost:8000/Tox-GHH.QDT78576.pdb
Here is one reference url for how to setup a local server - https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
