### ISSUE TITLE
Highlight/select on blob-ified str JSON

### ISSUE THREAD

**Issue by sacdallago** [molstar/pdbe-molstar#60]
Hi folks,

thanks for the great tooling :) I have a bit of a custom setup whereby I get the structure (PDB; from ColabFold/AF2) as string through some API in JSON format. I managed to BLOB-ify and URL-ify the string so that the component loads it. Here's the Plunker: https://plnkr.co/edit/aoXJPfblSLSwwv1X

I'm wondering how I could select/highlight a stretch of residues, but I seem to be unable to get it right. The console reads:
```
index.js?9b0a:148 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'managers')
    at PDBeMolstarPlugin.eval (index.js?9b0a:148:1)
    at step (tslib.es6.js?9ab4:102:1)
    at Object.eval [as next] (tslib.es6.js?9ab4:83:46)
    at eval (tslib.es6.js?9ab4:76:1)
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.js?9ab4:72:1)
    at Object.select (index.js?9b0a:136:41)
    at (index):76:29
```

I suppose I'm not able to "select" the right structure object, but I'm also unsure what the `entity_id` will be. On that note, minor one: any chance there's some options I can pass to set the name of the molecule? The "blob..." looks meh:

![image](https://user-images.githubusercontent.com/6240943/174278112-fd65ec22-ad10-46a4-ac90-fe8a3d00131f.png)

Thanks!! :)

**Comment by mandarsd** [comment]
Hi,
You are trying to do the selection before the 3D view render complete.
Subscribing to loadComplete custom event will properly handle this case
```
viewerInstance.events.loadComplete.subscribe(() => {
        viewerInstance.visual.select({
          data: [{
            entity_id: '1',
            struct_asym_id: 'A',
            start_residue_number: 1,
            end_residue_number: 2,
          }]
        }) 
      });
```
I'll add a feature request to the project plans to consider adding an option for molecule name
