### ISSUE TITLE
Add support for multiple PDB files as well as SDF files

### ISSUE THREAD

**Issue by GrayWasTaken** [molstar/pdbe-molstar#63]
I think a worthwhile feature would be to add support for displaying multiple PDB files simultaneously as well as SDF files. For example right now I'm trying to display a protein structure as well as a ligand that binds to a specific part of that structure (SDF file format).

As of right now I wasn't able to find a way to do this with PDBe-molstar but I know this is possible using https://www.rcsb.org/3d-view.

**Comment by GrayWasTaken** [comment]
There also seems to be an issue regarding loading cif files that contain ligands within them. For some reason only parts of the a single chain are loading.

**Comment by mandarsd** [comment]
Hi, you could load multiple structures in the PDBe instance. 
Here is a demo displaying a PDB and SDF file - https://embed.plnkr.co/plunk/dI7Oy7zLaKLEymtn

Regarding the issue of the cif files. Could you please try loading the files here - https://molstar.org/viewer/ and if you still see some parts missing then raise a ticket here - https://github.com/molstar/molstar/issues with some example cif files for debugging

**Comment by GrayWasTaken** [comment]
After updating to the latest version everything works perfectly thanks.
