### ISSUE TITLE
Coloring chains by arbitrary values

### ISSUE THREAD

**Issue by GrayWasTaken** [molstar/pdbe-molstar#65]
I was wondering if PDBe molstar had support for coloring entire chains by some arbitrary value (e.g., values within b factor fields). I want to have a single chain protein and a vector of numbers of the same length that where each element corresponds to a residue within the chain. I want to color structure similar to how the AlphaFold2 plddt values are colored by specifying color stops.

Is this currently possible in the current version of PDBe molstar? If not I'd like to request it as a feature since coloring structures with values such as summed PAE would be incredibly useful.

**Comment by bisejdiu** [comment]
I don't know how time-consuming the implementation is, but I think this feature request is quite important!  

The `focus`, `highlight`, and `select` features would become more powerful if, for instance, the `residue_number` parameter could accept an array, and we could provide an equal length array to the `colors` param.  
 
Conceptually, to me, this is not much different than the existing AlphaFold coloring theme, only exposing an API to do it for only a selection of residues, and with custom per-residue user-provided colors.

**Comment by GrayWasTaken** [comment]
Agreed, hypothetically this shouldn't be too tricky since the coloring by plddt from the aphafold view basically already implements this.

**Comment by mandarsd** [comment]
Hi both,
Thanks for the possible feature discussion. we recommend people to refer to both PDBe and RCSB implementations of Mol* to create their own similar plugins with required customizations like a new theme here. This way you could also reduce the final build size by removing the unnecessary modules.

I've added this feature request to our project catalog so that it will get discussed when we get the bandwidth to work on PDBe implementation enhancement.

**Comment by GrayWasTaken** [comment]
Hi @mandarsd,

Sorry about the late reply. I really do believe this to be an important feature to add and I've decided that I might make an attempt in the next couple weeks at adding the feature directly myself (granted I'm not a typescript developer).

Is there any official documentation for making plugins for PDBe and/or do you have any recommendations as to the best ways one should go about implementing such a feature?
