### ISSUE TITLE
Protein gets merged with ligand structure, even when they are separated by TER

### ISSUE THREAD

**Issue by saalim-ihub** [molstar/pdbe-molstar#66]
I am trying to view the local .pdb structure containing protein and ligand separated by TER using the molstar JS plugin. But for a few complexes, the protein is getting merged with the ligand structure. 

![Screenshot from 2022-09-02 07-00-25](https://user-images.githubusercontent.com/107020926/188040321-5215cbc7-0162-4e09-be5d-1d322343c9fe.png)

What could be the issue? I have used the following options, here `uurl` is a string which contains the URL of .pdb from localhost.

```
var options = {
        customData:{ url: uurl, format: 'pdb', binary:false },
        hideControls:true,
        expanded:false,
        hideExpandIcon:false,
        AnimationEffect:true,
        domainAnnotation:true,
        landscape:true}
```

**Comment by mandarsd** [comment]
Duplicate - Discussion link - https://github.com/molstar/molstar/issues/549
