### ISSUE TITLE
Not able to visualize protein structures which are present in my local system (in my computer) into my own html page using molstar.

### ISSUE THREAD

**Issue by gigity-gigity** [molstar/pdbe-molstar#67]
Dear Sir/ma'am,
I am trying to plugin molstar into my website as a visualization tool to visualize some of the structures I have modeled on my own. When using Plugin parameters (options), i.e customData to get data from my computer and visualize it on my website, I am getting this error "GET /home/supremeleader/visualization/A0A0A0CIP3.cif" Error (404): "Not found." I have just learned javascript and website development. Can you please help me with this issue so I can visualize the modeled protein on my website using molstar. Thank you in advance.

I have been using this script from documentation to visualize it:
var options = {
customData:{url:'/home/supremeleader/visualization/A0A0A0CIP3.cif',format:'cif'}}
error: "GET /home/supremeleader/visualization/A0A0A0CIP3.cif" Error (404): "Not found"

Please let me know which option I should use and any format syntax to visualize the protein in my system in my database.

Prashant Upadhyay
PhD
Indian Institute of Technology Kanpur

**Comment by mandarsd** [comment]
Duplicate - already discussed here - https://github.com/molstar/molstar/issues/551
