### ISSUE TITLE
Does the alphafoldView support only the cif file format?

### ISSUE THREAD

**Issue by Fx-Ren** [molstar/pdbe-molstar#69]
Does the alphafoldView support only the cif file format?

I download a pdb file from AlphaFold DB, but the plddt colormap did not work. How to visualize pdb file with alphafoldView.

**Comment by mandarsd** [comment]
Hi, The pLDDT data needed for the AlphaFold DB view theme is only available in the cif file, so the theme will appear when cif files are loaded with alphafold view

**Comment by halilakin** [comment]
Hi @mandarsd. Can confidence coloring be enabled with a PDB file where the pLDDT is stored in one of the columns (i.e. b-factor)? 

Is it possible to do this with custom code?

**Comment by mandarsd** [comment]
Details answered here - https://github.com/molstar/pdbe-molstar/issues/73
