### ISSUE TITLE
loading multiple structures loses non-covalent interaction rendering. Can it be maintained?

### ISSUE THREAD

**Issue by ljmartin** [molstar/pdbe-molstar#71]
Hi PDBe-Molstar,
Thanks for a great package. I'd like to load a protein structure (PDB), then separately a ligand structure (SDF). I'd like also to visualize the non-covalent interactions, as would be done with `ligandView` or by clicking on the ligand in a full single structure. 

However, when loading the structures separately, the non-covalent interactions aren't visualized. Is there any way to maintain these? 

Compare, for example, the ligand view of retinoic acid in 1CBS with the two loaded separately. [Example ligand interactions are here](https://www.rcsb.org/3d-view/1CBS?preset=ligandInteraction&label_asym_id=B) - basically hydrogen bonding between the carboxylic acid and the tyrosine and arginine is of interest. 

Doing the same in pdbe-molstar doesn't show the hydrogen bonding interactions, presumably because the molecules are considered separate, and not just non-bonded (see below for example).

Thanks

Example HTML follows. Note that, because I'm including the raw PDB and SDF data as plaintext blobs, it's a bit long. It's also worth noting that, when doing this, CPU usage appears pinned to ~100%. 

[here's a plunker](https://plnkr.co/edit/Wc0FUQSMsEeLKV8M?open=lib%2Fscript.js)

**Comment by mandarsd** [comment]
Hi,
You are right about why the interactions are not shown. Unfortunately PDBe implementation has no support for such functionality. You'll have to write your own Mol* plugin to accomplish it. The discussion here - https://github.com/molstar/molstar/issues/578 might be a good reference for you.

**Comment by ljmartin** [comment]
Thanks a lot @mandarsd for the molstar link - that will work.
