### ISSUE TITLE
Support a list of residue ids in visual methods

### ISSUE THREAD

**Issue by HubLot** [molstar/pdbe-molstar#74]
Hi,

Thanks for the work on this Mol* implementation!

I would like to be able to give a list of residus ids or number for the visual methods (select, focus, highlights) described here (https://github.com/molstar/pdbe-molstar/wiki/3.-Helper-Methods), like the `atom_id` parameter.

Is it easily doable ?

Thanks

**Comment by mandarsd** [comment]
Hi,
I've added this request to our work backlog.
