### ISSUE TITLE
Drag and Drop of the second PDB file fails on existing PDB render

### ISSUE THREAD

**Issue by navashiva** [molstar/pdbe-molstar#78]
**Issue** 
While attempting to render the second PDB file through HTML drag and drop functions on the existing PDB file viewer the second PDB file rendering fails. Following is the error message in the web console:-
`index.js?9b0a:112 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Object.applySettings (index.js?9b0a:112:1)
    at PDBeMolstarPlugin.eval (index.js?9b0a:593:1)
    at step (tslib.es6.js?9ab4:102:1)
    at Object.eval [as next] (tslib.es6.js?9ab4:83:46)
    at fulfilled (tslib.es6.js?9ab4:73:43)`

**Expected Behavior** 
On the drop of the second PDB file on the previous PDB file viewer, the viewer should clean the canvas and render the second PDB file successfully.

**Actual Behavior**
On the drop of the second PDB file on the previous PDB file viewer, the previous PDB file still renders.

_Note: For a demonstration of the issue, refer to the [following](https://pdbe-molstar-dnb-issue.s3.amazonaws.com/pdbe-molstar-dnb-issue.html) HTML file._

**Comment by mandarsd** [comment]
Sorry, your expected behavior would not work as the PDBe implementation is not intended to handle drag and drop, and multiple structure files.
