### ISSUE TITLE
Plane/disc implementation

### ISSUE THREAD

**Issue by S-Gutierrez** [molstar/pdbe-molstar#79]
Hello,
I am interested in the visualization of a disc by adding a plane measurement or as done in the ANVIL extension of Molstar used in RCSB:
 
https://github.com/molstar/molstar/tree/master/src/extensions/anvil

<img width="585" alt="membrane-hover" src="https://user-images.githubusercontent.com/77106361/208671473-d7965995-ce6f-4d96-8c4b-95d490a23b1d.png">

I tried to implement, on this version of Molstar, a class that models a disc in a given location. I used the code above as a reference. However, my knowledge of JS/CSS/Html is limited.

Can it be done in the current version? If not, it would be great to receive guidance on implementing this functionality, keeping in mind that I am not accustomed to programming in JS/CSS/Html.

Thank you for your time and consideration in addressing this issue.

Regards,

Santiago

**Comment by mandarsd** [comment]
Hi Santiago,
PDBe wrapper does not have this feature. Could you please check about this in the Molstar project [here](https://github.com/molstar/molstar/issues)
