### ISSUE TITLE
Enable the visualization of more molecules simultaneously

### ISSUE THREAD

**Issue by Firingam** [molstar/pdbe-molstar#84]
Hi,
is it possible to plot two different molecules, e.g. two proteins or two RNAs, and overlay them with Mol* as a JS component?
Thank you in advance

**Comment by mandarsd** [comment]
Hi,
Here is the link for the demo showing how to load multiple structures - https://embed.plnkr.co/plunk/dI7Oy7zLaKLEymtn

**Comment by Firingam** [comment]
Hi, thank you for your reply.
If I wanted to superimpose two similar proteins? Is there a possibility?

**Comment by mandarsd** [comment]
Sorry the PDBe JS component does not have such a feature. But you could write your own instance to do that.
Please refer to the basic wrapper examples in the Mol* repo. It has a method demonstrating superposition  -
https://github.com/molstar/molstar/tree/master/src/examples/basic-wrapper
https://github.com/molstar/molstar/blob/master/src/examples/basic-wrapper/superposition.ts
