### ISSUE TITLE
new window.PDBeMolstarPlugin more than once reported an error 

### ISSUE THREAD

**Issue by xueerli** [molstar/pdbe-molstar#87]
index.js:347 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'customState')

this.plugin is undefined
![image](https://github.com/molstar/pdbe-molstar/assets/35445052/d95813c9-62e6-4bcf-bb12-f9b36e9711e9)

**Comment by xueerli** [comment]
Can I create multiple viewers on a page?

**Comment by shaohuaY** [comment]
Did your project report an error?
"GET /build/pdbe-molstar-plugin-3.1.1.js" Error (404): "Not found"

**Comment by midlik** [comment]
Hi, it might be the same issue as here: https://github.com/molstar/pdbe-molstar/issues/94
