### ISSUE TITLE
Loading custom pdb

### ISSUE THREAD

**Issue by MIHassanLab** [molstar/pdbe-molstar#92]
I am trying to use a PDB file I have as a docked complex. I wish to visualize this using molstar JS plugin. However, even using 

`customData: { url:"ProteinComplex.pdb", format: "pdb", binary:false}`

I am unable to load the PDB file. Please help me out! (I am using the PDBe Mol* JS Plugin Demo file as the template)

Thanks in advance.

**Comment by MIHassanLab** [comment]
https://github.com/molstar/molstar/issues/551#issue-1365629374

Actually nevermind

**Comment by orangeSi** [comment]
fixed it at https://github.com/molstar/pdbe-molstar/issues/95
