### ISSUE TITLE
Can v3.1.3 being published to npm registry?

### ISSUE THREAD

**Issue by milanow** [molstar/pdbe-molstar#99]
Hi im using pdbe-mostar through npm registry, however it seems that I cannot properly import PDBeMolstarPlugin from "pdbe-molstar"@v3.1.2, I checked the latest version on Github where PDBeMolstarPlugin is properly exported. Can you publish and release the latest version to npm? Thanks

This way I don't need to reference *.js file in my <head>

**Comment by midlik** [comment]
Hi, in the meantime we released 3.1.3 on npm, and 3.2.0 is now also available.
